- name: installing nginx
  ansible.builtin.dnf:
    name: nginx
    state: latest

- name: starting and enabiling nginx
  ansible.builtin.service:
    name: nginx
    state: started
    enabled: yes

- name: removing all files in html folder
  ansible.builtin.file:
    path: rm -rf /usr/share/nginx/html/*
    state: absent

- name: downloading and unarchive
  ansible.builtin.unarchive:
    src: https://expense-builds.s3.us-east-1.amazonaws.com/expense-frontend-v2.zip
    dest: /usr/share/nginx/html
    remote_src: yes

- name: copying expense conf file
  ansible.builtin.template:
    src: expense.conf.j2
    dest: /etc/nginx/default.d/expense.conf
  notify:
  - restarting nginx

# - name: restarting nginx
#   ansible.builtin.service:
#     name: nginx
#     state: restarted